api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "pack-discount"
type = "function"
uid = "8e1b15d1-8668-f5ca-aa3d-104289410052041f028e"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
